# Steps:
# 1. Fill web-production image.

version: "3.5"

services:
  web-production:
    image: gcr.io/geniem-production/client-opinvoimala-frontend:production-latest

    container_name: web-production

    hostname: ${HOSTNAME_PREFIX}-web-production

    restart: "no"

    networks:
      - backend-production

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/devops/logs/production/web:/mnt/devops/logs/production/web

networks:
  backend-production:
    external:
      name: backend-production