# Steps:
# 1. Fill web-stage image.

version: "3.5"

services:
  web-stage:
    image: gcr.io/geniem-stage/client-opinvoimala-frontend:stage-latest

    container_name: web-stage

    hostname: ${HOSTNAME_PREFIX}-web-stage

    restart: "no"

    networks:
      - backend-stage

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/devops/logs/stage/web:/mnt/devops/logs/stage/web

networks:
  backend-stage:
    external:
      name: backend-stage